// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildModsInGame(arg1, arg2) {
  return window['go']['main']['App']['BuildModsInGame'](arg1, arg2);
}

export function BuildModsInLocal(arg1, arg2) {
  return window['go']['main']['App']['BuildModsInLocal'](arg1, arg2);
}

export function GetModList() {
  return window['go']['main']['App']['GetModList']();
}

export function PullCk3GameFiles() {
  return window['go']['main']['App']['PullCk3GameFiles']();
}
