// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildModsInGame():Promise<void>;

export function BuildModsInLocal():Promise<void>;

export function PullCk3GameFiles():Promise<void>;
