// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildModsInGame() {
  return window['go']['main']['App']['BuildModsInGame']();
}

export function BuildModsInLocal() {
  return window['go']['main']['App']['BuildModsInLocal']();
}

export function GetModList() {
  return window['go']['main']['App']['GetModList']();
}

export function PullCk3GameFiles() {
  return window['go']['main']['App']['PullCk3GameFiles']();
}
