// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {configs} from '../models';

export function BuildModsInGame(arg1:Array<string>,arg2:boolean):Promise<void>;

export function BuildModsInLocal(arg1:Array<string>,arg2:boolean):Promise<void>;

export function GetModList():Promise<configs.ModType>;

export function Greet(arg1:string):Promise<string>;

export function PullCk3GameFiles():Promise<void>;
